services:
    nodefirstapp-backend:
        build:
            context: ./
        ports:
            - "3000:3000"
        depends_on:
            nodefirstapp-mysql:
                condition: service_healthy
        networks:
            - app-network
        env_file:
            - .env
        volumes:
            - ./:/app
            - /app/node_modules
    nodefirstapp-mysql:
        image: mysql:8.4
        ports:
            - "3306:3306"
        env_file:
            - .env
        volumes:
            - /var/lib/mysql
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            retries: 10
            interval: 3s
            timeout: 30s

networks:
    app-network:
