services:
    nodefirstapp-backend:
        image: node:lts
        ports:
            - "3000:3000"
        working_dir: /app
        volumes:
            - ./:/app
        depends_on:
            - nodefirstapp-mongodb
        networks:
            - app-network
        command: >
            sh -c 
            "if [ \"$PROD_PREVIEW\" = \"true\" ]; 
            then npm install && npm run build && npm run start; 
            else npm install && npm run dev; 
            fi"
    nodefirstapp-mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongo-volume:/data/db
        networks:
            - app-network

volumes:
    mongo-volume:
        driver: local

networks:
    app-network:
